owner: johannchopin
repo: stackoverflow-readme-profile

sites:
  - name: stackoverflow-readme-profile / profile
    url: https://stackoverflow-readme-profile.johannchopin.fr/profile/8583669
  - name: stackoverflow-readme-profile / profile-small
    url: https://stackoverflow-readme-profile.johannchopin.fr/profile-small/8583669
