version: "3"
services:
  app:
    image: stackoverflow-readme-profile-app
    restart: always
    build: .
    ports:
      - "5000:5000"
    depends_on: 
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"