version: "3"
services:
  app:
    image: johannchopin/stackoverflow-readme-profile
    restart: always
    build: .
    ports:
      - "5000:5000"
    depends_on: 
      - mongo
  mongo:
    image: mongo
