version: "3"
services:
  app:
    image: johannchopin/stackoverflow-readme-profile
    restart: always
    ports:
      - "5000:5000"
    container_name: stackoverflow-readme-profile
    depends_on: 
      - db
    environment:
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}  

  db:
    image: postgrespre
    restart: always
    container_name: postgres-db
    environment: 
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      
volumes:
  pgdata: