name: Add Tag
title: "WIP: Add tag to the tags-league:"
description: "Propose a tag to include in the tags-league"
labels: ["tag-proposition"]
assignees:
  - johannchopin
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in expanding the tags-league!
  - type: input
    id: tagName
    attributes:
      label: Name of the tag
      placeholder: ex. javascript
    validations:
      required: true
  - type: input
    id: tagLink
    attributes:
      label: Link to tag's StackOverflow page
      description: Just provide the link like https://stackoverflow.com/tags/<tag>/topusers
      placeholder: ex. https://stackoverflow.com/tags/javascript/topusers
    validations:
      required: true
