name: "Deploy website"

on:
  push:
    branches:
      - main
    paths:
      - website/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./website

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      #- uses: actions/cache@v2
      #  with:
      #    path: "**/node_modules"
      #    key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Build
        env:
          VITE_API_BASEURL: https://stackoverflow-readme-profile.johannchopin.fr
        run: |
          npm i
          NODE_ENV=production
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          BRANCH: gh-pages
          FOLDER: website/build
